### ISSUE TITLE
捉虫，以及一些建议

### ISSUE THREAD

**Issue by CaptLeaf** [CSneko/JustARod#9]
捉虫，发青效果（effect.more_end_rod.estrus）没有中文翻译
建议：1.希望能够在后续的更新中加上无限耐久这一属性（或者增加物品耐久值，相较于前代mod末地烛太容易爆了），实测采用游戏内无法破坏tag和耐久255tag无效，总会在使用到某一固定次数时无法继续产生效果，即耐久归零；耐久III附魔有用但不多。（如红石末地烛就是1002次）（现在这个版本倒是类似于那种用后即焚的玩意）
2.希望能够丰富一些插入末地烛后在聊天框中给予的反馈，类似于您所制作的more end rod中的那些一样

**Comment by CSneko** [comment]
好的 :)
